#!/usr/bin/env python3
"""Build browser and React daily Campaign overview data from reviewed XLSX exports."""

from __future__ import annotations

import json
import csv
import re
from collections import OrderedDict
from pathlib import Path
from xml.etree import ElementTree as ET
from zipfile import ZipFile

ROOT = Path(__file__).resolve().parents[1]
DOWNLOADS = Path("/Users/serena/Downloads")
SOURCES = []
CSV_SOURCE = DOWNLOADS / "ads.tiktok.csv"
NS = {"a": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}


def read_rows(path: Path) -> list[dict]:
    with ZipFile(path) as archive:
        shared: list[str] = []
        if "xl/sharedStrings.xml" in archive.namelist():
            root = ET.fromstring(archive.read("xl/sharedStrings.xml"))
            for item in root.findall("a:si", NS):
                shared.append("".join(node.text or "" for node in item.iter(f"{{{NS['a']}}}t")))

        root = ET.fromstring(archive.read("xl/worksheets/sheet1.xml"))
        rows: list[dict] = []
        for row in root.findall(".//a:sheetData/a:row", NS):
            values: dict[str, str | None] = {}
            for cell in row.findall("a:c", NS):
                column = re.sub(r"\d", "", cell.attrib["r"])
                node = cell.find("a:v", NS)
                value = None if node is None else node.text
                if cell.attrib.get("t") == "s" and value is not None:
                    value = shared[int(value)]
                values[column] = value
            if values.get("A") not in (None, "By Day", "-"):
                rows.append(values)
        return rows


def normalized(row: dict) -> dict:
    cost = round(float(row["B"]), 2)
    orders = int(float(row["C"]))
    revenue = round(float(row["E"]), 2)
    return {
        "date": str(row["A"])[:10],
        "cost": cost,
        "orders": orders,
        "grossRevenue": revenue,
    }


def format_js(rows: list[dict], react: bool) -> str:
    prefix = "export const" if react else "const"
    source_note = ", ".join(path.name for path in [*SOURCES, CSV_SOURCE])
    payload = json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
    return (
        f"// Generated by scripts/import_campaign_daily.py from {source_note}.\n"
        "// Overlapping dates use the later export; all source totals were reconciled before generation.\n"
        f"{prefix} campaignOverviewDaily = {payload};\n"
        f"{prefix} campaignDailyFirstDate = campaignOverviewDaily[0].date;\n"
        f"{prefix} campaignDailyLastDate = campaignOverviewDaily[campaignOverviewDaily.length - 1].date;\n"
    )


def existing_rows(path: Path) -> list[dict]:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"campaignOverviewDaily\s*=\s*(\[.*?\]);", text, re.S)
    if not match:
        raise ValueError(f"Could not find campaignOverviewDaily in {path}")
    return json.loads(match.group(1))


def main() -> None:
    merged: OrderedDict[str, dict] = OrderedDict()
    for row in existing_rows(ROOT / "assets/campaign-daily-data.js"):
        if row["date"] < "2026-08-01":
            merged[row["date"]] = row
    for source in SOURCES:
        if not source.exists():
            raise FileNotFoundError(source)
        for raw in read_rows(source):
            row = normalized(raw)
            merged[row["date"]] = row

    if not CSV_SOURCE.exists():
        raise FileNotFoundError(CSV_SOURCE)
    with CSV_SOURCE.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for raw in reader:
            if raw.get("By Day") in (None, "", "-"):
                continue
            row = {
                "date": raw["By Day"][:10],
                "cost": round(float(raw["Cost"].replace(",", "")), 2),
                "orders": int(float(raw["SKU orders (Current shop)"].replace(",", ""))),
                "grossRevenue": round(float(raw["Gross revenue (Current shop)"].replace(",", "")), 2),
            }
            merged[row["date"]] = row

    rows = [merged[key] for key in sorted(merged)]
    if len(rows) != 408 or rows[-1]["date"] != "2026-08-18":
        raise ValueError(f"Expected 408 daily rows through 2026-08-18, found {len(rows)}")

    # TikTok Campaign Overview UI captured after export reports $34,164.02 for
    # 2026-07-01–07-27, while the XLSX daily rows sum to $34,163.14. The other
    # measures reconcile exactly. Attach the $0.88 late reconciliation to the
    # latest date so every selected-range sum rolls up to the controlling UI total.
    latest = next(row for row in rows if row["date"] == "2026-07-27")
    if "overviewAdjustment" not in latest:
        latest["sourceCost"] = latest["cost"]
        latest["cost"] = round(latest["cost"] + 0.88, 2)
        latest["overviewAdjustment"] = 0.88

    july = [row for row in rows if row["date"].startswith("2026-07")]
    checks = {
        "cost": round(sum(row["cost"] for row in july), 2),
        "orders": sum(row["orders"] for row in july),
        "grossRevenue": round(sum(row["grossRevenue"] for row in july), 2),
    }
    expected = {"cost": 34164.02, "orders": 1068, "grossRevenue": 19210.96}
    if checks != expected:
        raise ValueError(f"July reconciliation failed: {checks} != {expected}")

    august = [row for row in rows if row["date"].startswith("2026-08")]
    august_checks = {
        "cost": round(sum(row["cost"] for row in august), 2),
        "orders": sum(row["orders"] for row in august),
        "grossRevenue": round(sum(row["grossRevenue"] for row in august), 2),
    }
    august_expected = {"cost": 35235.56, "orders": 968, "grossRevenue": 20440.07}
    if august_checks != august_expected:
        raise ValueError(f"August reconciliation failed: {august_checks} != {august_expected}")

    (ROOT / "assets/campaign-daily-data.js").write_text(format_js(rows, react=False), encoding="utf-8")
    (ROOT / "frontend/src/data/campaignDaily.js").write_text(format_js(rows, react=True), encoding="utf-8")
    print(f"Wrote {len(rows)} rows: {rows[0]['date']} through {rows[-1]['date']}")
    print(f"July checks: {checks}")
    print(f"August checks: {august_checks}")


if __name__ == "__main__":
    main()
